// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgdwGCjDaERIQtV-5ECm3DhRU5DiJsJgE',
    appId: '1:369023582992:web:3e5e3ceba22af8deea1b95',
    messagingSenderId: '369023582992',
    projectId: 'spendsense-730ea',
    authDomain: 'spendsense-730ea.firebaseapp.com',
    storageBucket: 'spendsense-730ea.firebasestorage.app',
    measurementId: 'G-0GNK8YPCBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFKp4zD7FQbeYnMVpV9b8O4zbyG20JQU',
    appId: '1:369023582992:android:c3489b4326f445adea1b95',
    messagingSenderId: '369023582992',
    projectId: 'spendsense-730ea',
    storageBucket: 'spendsense-730ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9txllG6txJYolOE91D8bxwslTAa6LwpA',
    appId: '1:369023582992:ios:44c0570260fa7a5eea1b95',
    messagingSenderId: '369023582992',
    projectId: 'spendsense-730ea',
    storageBucket: 'spendsense-730ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9txllG6txJYolOE91D8bxwslTAa6LwpA',
    appId: '1:369023582992:ios:44c0570260fa7a5eea1b95',
    messagingSenderId: '369023582992',
    projectId: 'spendsense-730ea',
    storageBucket: 'spendsense-730ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgdwGCjDaERIQtV-5ECm3DhRU5DiJsJgE',
    appId: '1:369023582992:web:e6dfd04aec2dfbecea1b95',
    messagingSenderId: '369023582992',
    projectId: 'spendsense-730ea',
    authDomain: 'spendsense-730ea.firebaseapp.com',
    storageBucket: 'spendsense-730ea.firebasestorage.app',
    measurementId: 'G-Y8M03X1TPZ',
  );
}
